<?php

namespace ContainerF4Vlvxs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_78L1jldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.78L1jld' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.78L1jld'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'conferenceRepository' => ['privates', 'App\\Repository\\ConferenceRepository', 'getConferenceRepositoryService', false],
        ], [
            'conferenceRepository' => 'App\\Repository\\ConferenceRepository',
        ]);
    }
}
