<?php

namespace Container8xK1oqa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_3qU50ktService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.3qU50kt' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.3qU50kt'] = \current([0 => (\dirname(__DIR__, 4).'/public/uploads/photos')]);
    }
}
