<?php

namespace Container8xK1oqa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zl5YrlCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zl5YrlC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zl5YrlC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'conference' => ['privates', '.errored..service_locator.Zl5YrlC.App\\Entity\\Conference', NULL, 'Cannot autowire service ".service_locator.Zl5YrlC": it references class "App\\Entity\\Conference" but no such service exists.'],
            'conferenceRepository' => ['privates', 'App\\Repository\\ConferenceRepository', 'getConferenceRepositoryService', false],
            'photoDir' => ['privates', '.value.3qU50kt', 'get_Value_3qU50ktService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'conference' => 'App\\Entity\\Conference',
            'conferenceRepository' => 'App\\Repository\\ConferenceRepository',
            'photoDir' => '?',
        ]);
    }
}
