<?php

namespace Container8xK1oqa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConferenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Zl5YrlC.App\Entity\Conference' shared service.
     *
     * @return \App\Entity\Conference
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Zl5YrlC": it references class "App\\Entity\\Conference" but no such service exists.');
    }
}
