<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF4Vlvxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF4Vlvxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF4Vlvxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF4Vlvxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF4Vlvxs\App_KernelDevDebugContainer([
    'container.build_hash' => 'F4Vlvxs',
    'container.build_id' => '032c75ae',
    'container.build_time' => 1644923391,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF4Vlvxs');
